# Welcome to Jekyll!

# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/


title: Shoelace Games | Indie Developer
email: your-email@example.com
description: >-
    Explore Ryan Pierce's unique indie games, blending rich storytelling with immersive gameplay. Dive into his world of innovative, story-driven gaming experience.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ShoelaceGames
github_username: Ryan-Pierce-Shoelace

# site vars
branding:
    name: "Shoelace Games"
    tag: "Indie Developer"
    logo: "/assets/images/logo.svg"

author:
    name: "Ryan Pierce"
    bio: "An indie game developer."
    location: "Toronto, Canada"
    github: "https://github.com/Ryan-Pierce-Shoelace"
    itchio: "https://shoelace.itch.io/"
    avatar: "/assets/images/bio-photo.jpg"

hero:
    title: "Shoelace Games"
    subtitle: "Coded with form and function"

collections:
    games:
        output: true
        permalink: /games/:path/

# Build settings
theme: minima
plugins:
    - jekyll-feed

  
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
